const employee = {
  name: "Nishana",
  salary: 25000,
  role: "React Developer"
};

const { name, role } = employee;

console.log(name);
console.log(role);
//map objects
//set objects 
// this two are the new data structures in ES6.
// this two are the new data structures in ES6.
//lazyday
//lazyday 2 
//collection performance
//postman setup
//cxo-customer-kpi cards detail page
//cxo-customer-delivery-detail page and helpfile
//cx-customer-each-widget-detail page 
//canva
//helpfilechanges